### ISSUE TITLE
%FileName% expanding in lower case

### ISSUE THREAD

**Issue by haymansfield** [rubicon-oss/LicenseHeaderManager#49] opened 2016-06-02 11:30 UTC
%FileName% expands to lower case filename.

**Comment by FlorianDecker** [comment] 2016-06-02 11:34
Hi haymannsfield!

Thanks for the Report! If i understand your issue correctly it is a duplicate of #37 , so i am going to close this one. If you have anything to add feel free to comment on the issue.

Regards,
Florian

**Closed by FlorianDecker** 2016-06-02 11:34 UTC
