### ISSUE TITLE
Error: Cannot create a stable subkey under a volatile parent key

### ISSUE THREAD

**Issue by Daxito** [rubicon-oss/LicenseHeaderManager#70] opened 2017-04-26 18:48 UTC
trying to installing it for VS 2017 Community, I get this error:

Error: Cannot create a stable subkey under a volatile parent key

Is there any reason?
Thanks!

**Comment by FlorianDecker** [comment] 2017-05-02 08:31
Hi! Sorry for the late reply.

Thats an entirely new error message, never seen that one before. Googling suggests that there is something wrong with some registry entries (https://technet.microsoft.com/en-us/windows/ms833793.aspx). 

As we dont really control what happens when the extension gets installed, my best guess would be that there is some problem with your visual studio installation. Do you get this error only when installing the LicenseHeaderManager or also with other extensions?

**Comment by FlorianDecker** [comment] 2017-12-11 09:52
Closing this, as it seems like an isolated issue and we cannot reproduce it.

**Closed by FlorianDecker** 2017-12-11 09:52 UTC
