### ISSUE TITLE
Create VSIX package with support for VS2017

### ISSUE THREAD

**Issue by MichaelKetting** [rubicon-oss/LicenseHeaderManager#57] opened 2016-11-21 07:15 UTC
VS2017 requires a VSIX package that specifies the features used.

Note that VSIX packages created with VS2017 are backwards compatible down to VS2012. The current version still supports VS2010. We will need to provide a separate installer vor VS2010.

https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes#vside

**Comment by squideyes** [comment] 2017-02-10 21:32
In case you haven't seen the error that's thrown when trying to do an install in VS2017 RC:

2/10/2017 4:30:40 PM - Microsoft VSIX Installer
2/10/2017 4:30:40 PM - -------------------------------------------
2/10/2017 4:30:40 PM - vsixinstaller.exe version:
2/10/2017 4:30:40 PM - 15.0.26206.0 built by: D15REL
2/10/2017 4:30:40 PM - -------------------------------------------
2/10/2017 4:30:40 PM - Command line parameters:
2/10/2017 4:30:40 PM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VSIXInstaller.exe,C:\Users\louis\Downloads\LicenseHeaderManager.vsix
2/10/2017 4:30:40 PM - -------------------------------------------
2/10/2017 4:30:40 PM - Microsoft VSIX Installer
2/10/2017 4:30:40 PM - -------------------------------------------
2/10/2017 4:30:40 PM - Failed to initialize settings for Isolated Shell C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\ssms.exe: Unable to find an entry point named '?' in DLL 'PkgdefMgmt.dll'.
2/10/2017 4:30:40 PM - Initializing Install...
2/10/2017 4:30:40 PM - Extension Details...
2/10/2017 4:30:40 PM - 	Identifier         : 4c570677-8476-4d33-bd0c-da36c89287c8
2/10/2017 4:30:40 PM - 	Name               : License Header Manager
2/10/2017 4:30:40 PM - 	Author             : rubicon IT GmbH
2/10/2017 4:30:40 PM - 	Version            : 1.7.2
2/10/2017 4:30:40 PM - 	Description        : An extension for adding license headers to source code files.
2/10/2017 4:30:40 PM - 	Locale             : en-US
2/10/2017 4:30:40 PM - 	MoreInfoURL        : https://github.com/rubicon-oss/LicenseHeaderManager
2/10/2017 4:30:40 PM - 	InstalledByMSI     : False
2/10/2017 4:30:40 PM - 	SupportedFrameworkVersionRange : [4.0,4.5]
2/10/2017 4:30:40 PM - 
2/10/2017 4:30:40 PM - 	SignatureState     : ValidSignature
2/10/2017 4:30:40 PM - 	SignedBy           : rubicon IT GmbH
2/10/2017 4:30:40 PM - 	Certificate Info   : 
2/10/2017 4:30:40 PM - 		-------------------------------------------------------
2/10/2017 4:30:40 PM - 		[Subject]       : CN=rubicon IT GmbH, O=rubicon IT GmbH, L=Wien, C=AT
2/10/2017 4:30:40 PM - 		[Issuer]        : CN=Go Daddy Secure Certificate Authority - G2, OU=http://certs.godaddy.com/repository/, O="GoDaddy.com, Inc.", L=Scottsdale, S=Arizona, C=US
2/10/2017 4:30:40 PM - 		[Serial Number] : 00F839EB5A51D3C149
2/10/2017 4:30:40 PM - 		[Not Before]    : 2/16/2016 9:54:38 AM
2/10/2017 4:30:40 PM - 		[Not After]     : 4/13/2019 5:04:55 AM
2/10/2017 4:30:40 PM - 		[Thumbprint]    : DC3E3B2CE9638CF55AA9A80F95FBEABA88A7C500
2/10/2017 4:30:40 PM - 
2/10/2017 4:30:40 PM - 	Supported Products : 
2/10/2017 4:30:40 PM - 		Microsoft.VisualStudio.Ultimate
2/10/2017 4:30:40 PM - 			Version : [10.0]
2/10/2017 4:30:40 PM - 		Microsoft.VisualStudio.Ultimate
2/10/2017 4:30:40 PM - 			Version : [11.0]
2/10/2017 4:30:40 PM - 		Microsoft.VisualStudio.Ultimate
2/10/2017 4:30:40 PM - 			Version : [12.0]
2/10/2017 4:30:40 PM - 		Microsoft.VisualStudio.Ultimate
2/10/2017 4:30:40 PM - 			Version : [14.0]
2/10/2017 4:30:40 PM - 		Microsoft.VisualStudio.Premium
2/10/2017 4:30:40 PM - 			Version : [10.0]
2/10/2017 4:30:40 PM - 		Microsoft.VisualStudio.Premium
2/10/2017 4:30:40 PM - 			Version : [11.0]
2/10/2017 4:30:40 PM - 		Microsoft.VisualStudio.Premium
2/10/2017 4:30:40 PM - 			Version : [12.0]
2/10/2017 4:30:40 PM - 		Microsoft.VisualStudio.Premium
2/10/2017 4:30:40 PM - 			Version : [14.0]
2/10/2017 4:30:40 PM - 		Microsoft.VisualStudio.Pro
2/10/2017 4:30:40 PM - 			Version : [10.0]
2/10/2017 4:30:40 PM - 		Microsoft.VisualStudio.Pro
2/10/2017 4:30:40 PM - 			Version : [11.0]
2/10/2017 4:30:40 PM - 		Microsoft.VisualStudio.Pro
2/10/2017 4:30:40 PM - 			Version : [12.0]
2/10/2017 4:30:40 PM - 		Microsoft.VisualStudio.Pro
2/10/2017 4:30:40 PM - 			Version : [14.0]
2/10/2017 4:30:40 PM - 
2/10/2017 4:30:40 PM - 	References         : 
2/10/2017 4:30:40 PM - 		-------------------------------------------------------
2/10/2017 4:30:40 PM - 		Identifier   : Microsoft.VisualStudio.MPF
2/10/2017 4:30:40 PM - 		Name         : Visual Studio MPF
2/10/2017 4:30:40 PM - 		Version      : [10.0,)
2/10/2017 4:30:40 PM - 		MoreInfoURL  : 
2/10/2017 4:30:40 PM - 		Nested       : No
2/10/2017 4:30:40 PM - 
2/10/2017 4:30:40 PM - Signature Details...
2/10/2017 4:30:40 PM - 	Extension is signed with a valid signature.
2/10/2017 4:30:40 PM - 
2/10/2017 4:30:40 PM - Searching for applicable products...
2/10/2017 4:30:40 PM - Found installed product - Global Location
2/10/2017 4:30:40 PM - Found installed product - Visual Studio Enterprise 2017 RC
2/10/2017 4:30:40 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by Convery** [comment] 2017-03-13 03:24
MSVC 2017 is now officially released. Any update on the packaging?

**Comment by MichaelKetting** [comment] 2017-03-13 07:01
Soonish, but I can't promise this week.

**Comment by MichaelKetting** [comment] 2017-03-25 09:42
Hi guys! I'm sorry, we're still stuck on getting the release packages signed and uploaded to the Visual Studio gallery. In the meantime, I've attached the unsigned packages to the GitHub release information:
* https://github.com/rubicon-oss/LicenseHeaderManager/releases/tag/1.7.3
* https://github.com/rubicon-oss/LicenseHeaderManager/releases/tag/2.0.0

**Comment by mechacrash** [comment] 2017-03-25 13:01
I installed the 2.0.0 pre-release to VS 2017 community and it's giving an error upon load: http://i.mechacrash.com/8RAffD5g.png
The activity log is as follows:
http://i.mechacrash.com/cVQ59SxL.txt

I compiled the source myself prior but was also getting issues (the extension simply did nothing) but assumed it was a fault on my part.

**Comment by Convery** [comment] 2017-03-25 14:56
It installs for me, but it doesn't automatically add a header to new files. In fact, if you manually right-click a filename and select "Add License Header" then Visual Studio creates a very helpful dialog box with `The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))`.

The only errors in the ActivityLog.xml:
```
  <entry>
    <record>326</record>
    <time>2017/03/25 14:46:25.746</time>
    <type>Error</type>
    <source>Extension Manager</source>
    <description>Extension will not be loaded because an extension with the same ID &apos;Microsoft.Windows.DevelopmentKit.Desktop&apos; is already loaded at C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\MICROSOFT\WINDOWS KITS\10\DESKTOP SDK\...</description>
    <path>C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\MICROSOFT\WINDOWS KITS\8.1\DESKTOP SDK\</path>
  </entry>
  <entry>
    <record>327</record>
    <time>2017/03/25 14:46:25.746</time>
    <type>Error</type>
    <source>Extension Manager</source>
    <description>Extension will not be loaded because an extension with the same ID &apos;Microsoft.Windows.DevelopmentKit.WindowsStore&apos; is already loaded at C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\MICROSOFT\WINDOWS KITS\10\WINDOWS STORE SDK\...</description>
    <path>C:\PROGRAM FILES (X86)\COMMON FILES\MICROSOFT\EXTENSIONMANAGER\EXTENSIONS\MICROSOFT\WINDOWS KITS\8.1\WINDOWS STORE SDK\</path>
  </entry>
  <entry>
    <record>427</record>
    <time>2017/03/25 14:46:40.434</time>
    <type>Error</type>
    <source>Color Theme Service</source>
    <description>The color &apos;Popup&apos; in category &apos;de7b1121-99a4-4708-aedf-15f40c9b332f&apos; does not exist.</description>
  </entry>
```

Microsoft Visual Studio Community 2017
Version 15.0.26228.9 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01586

**Comment by MichaelKetting** [comment] 2017-03-25 15:46
Hmm...It works with my VS 2017 Enterprise Edition and I think we also tested the Community Edition but @FlorianDecker  would have to answer that one. There's nothing obvious in the VS2017 compability changeset that would indicate a duplicate ID. This will require further testing. Could you please create a separate issue for this?

**Comment by FlorianDecker** [comment] 2017-03-27 15:20
@mechacrash i was able to reproduce your error with a fresh VS2017 , just not consistently. When i got the error and restarted VS, the LicenseHeaderManager worked without problems and the error did not appear again. Can you confirm this behaviour, or is the LicenseHeaderManager extension never loaded?

@Convery i could not reproduce your error and i am not sure if it is really an error produced by the VS2017 compatibility. Do you have other Visual Studio versions installed where you could test if the LicenseHeaderManager works correctly (with the same file)? As i dont think this is due to the VS2017 compatibility, we should move this discussion to #68

**Comment by mechacrash** [comment] 2017-03-27 18:58
When I tested, nothing worked. I attempted to start up VS multiple time and the extension never loaded. The activity log was always the same.

**Comment by FlorianDecker** [comment] 2017-03-28 10:58
@mechacrash hmhh, as it worked with my fresh VS2017 Community, i can think of two possible causes:

1. (most likely) Something in your installation is corrupt. You could try deleting the ComponentCacheFolder of VS2017 (as suggested [here](http://stackoverflow.com/questions/17574089/microsoft-visual-studio-package-did-not-load-correctly) and [here](http://stackoverflow.com/questions/31547947/packages-not-loading-after-installing-visual-studio-2015-rtm)).

Path should be something like 

> C:\Users\USERNAME\AppData\Local\Microsoft\VisualStudio\15.0_7bd986df\ComponentModelCache

2. (unlikely) Your VS2017 installation contains components which interfere with the LicenseHeaderManager package. 
Could you send me a list of your installed components so i can recreate your installation? For the list, open the Visual Studio Installer -> VS Community 2017 "Modify". On the right site, you have a "Summary" of the installed components. Easiest way to share is probably to screenshot it. 
It is a little bit far fetched, but when i tried to reproduce your error, as described above, it got triggered after changing some components.

**Comment by FlorianDecker** [comment] 2017-09-13 15:41
As we have VS2017 compatibility for a while now, i am closing this issue. If there are still problems with the installation, please open a new issue.

**Closed by FlorianDecker** 2017-09-13 15:41 UTC
Labels: feature

**Comment by FlorianDecker** [comment] 2017-10-25 16:53
@mechacrash #84 had the same issue as you i think. Please try out this unsigned version, it should fix the issue with the extension not loading.

[LicenseHeaderManager_unsigned.zip](https://github.com/rubicon-oss/LicenseHeaderManager/files/1415436/LicenseHeaderManager_unsigned.zip)
