### ISSUE TITLE
Crash with PHP Tools for Visual Studio

### ISSUE THREAD

**Issue by Dimigergo** [rubicon-oss/LicenseHeaderManager#32] opened 2016-04-07 14:49 UTC
When use the two plugins with each other the Visual Studio 2013/2015 will crash if you open a php project with some files or folders.

This case:
http://support.devsense.com/viewtopic.php?f=21&t=1429&p=6702&hilit=crash#p6702

But I have the same error with phpTools 1.19.8670 and LicenseHeaderManager 1.7.1.

Thanks.

**Comment by FlorianDecker** [comment] 2016-04-14 09:04
Hi Dimigergo,

thanks for the issue report! 
I am not sure if i am able reproduced your error correctly, my VS only crashed when clicking on the LicenseHeaderManager Command "Add Licenseheaders to all Files".(Which is bad enough). 

However, i think i found a fix for that. So maybe it also fixes the issue you described.

Do you maybe have an example repo floating around so i could test my local fix on your exact issue?

Cheers,
Florian

**Comment by Dimigergo** [comment] 2016-04-25 12:36
Hi Florian,

If you fix the crash you mentioned, I can try out in my system. I don't know how can I make an example, because I can't open the project with the phpTools and the LicenseHeaderManager plugins.

Thank you very much!

**Comment by FlorianDecker** [comment] 2016-04-26 06:27
Hi Dimigergo,

attached is a Debug Build with the fix. It has the same version number as the current release, so you have to deinstall the current LicenseHeaderManager Extension and then install this one.


[LicenseHeaderManagerDebgugBuild.zip](https://github.com/rubicon-oss/LicenseHeaderManager/files/236008/LicenseHeaderManagerDebgugBuild.zip)

**Comment by Dimigergo** [comment] 2016-04-26 08:07
Dear Florian,

I have downloaded the package, but it crashes too. :(

I also downloaded the source of the 1.7.1-release.zip, and start to debug the error.
- When I ran the debugger to start external program (devenv.exe) with /rootsuffix Exp there were no exception, and the php project opened fine. (but in this case, I can debug the project with breakpoints)
- When I run devenv.exe without /rootsuffix Exp args (I cannot use breakpoints) StackOverFlowException was come when starting the php project. 
The main thread stack shows me the following functions (every StackOverFlowException occured different positions, but it can helps):
- LicenseHeaderFinder.GetHeaderRecursive (object projectOrItem)
- String.ToLower method (I think in the GetLicenseHeaderDefinitions function).

Hope this helps.

**Comment by FlorianDecker** [comment] 2016-04-26 09:38
hmh, ok so not the easy solution then.

Ok these are interesting informations. But i still cant reproduce it here :( 

Does your VS crash on any PHP Project with Files and Folders?   

You should be able to set Breakpoints (when running deveenv.exe without /rootsuffix Exp) if you install the 1.7.1-release .vsix again. 
Because, when you Start devenv.exe without /rootsuffix Exp it does not deploy the extension. If the Extension installed in VS does not match exactly with the Extension you want to Debug, Breakpoints are not enabled. Installing the current Version again should fix that :)

Thanks for your help!

**Comment by Dimigergo** [comment] 2016-04-26 13:45
That's right! :)

When the GetHeaderRecursive (ProjectItem projectItem) function parameter is a folder the projectItem.Collection.Parent is the same folder. It will call the GetHeaderRecursive (object projectOrItem) with this (same) folder and it will couse the StackOverFlowException.

In my situation the crash occures when _addedItems in FinishedAddingItem contains a folder or a file with a parent folder.

**Comment by FlorianDecker** [comment] 2016-04-28 07:16
Perfect, with that information i was able to reproduce it and implement a workaround- i think. Please test it :)

[LicenseHeaderManager - DebugVersion.zip](https://github.com/rubicon-oss/LicenseHeaderManager/files/239987/LicenseHeaderManager.-.DebugVersion.zip)

**Comment by Dimigergo** [comment] 2016-04-28 07:59
It's perfect, everything works fine! :)

Thank you very much, I'm waiting for the release version.

Have a nice day!

**Comment by FlorianDecker** [comment] 2016-04-29 09:15
Fixed with #36 . 
Fix is pushed and 1.7.2 is going to be officially released some time soon :)

**Closed by FlorianDecker** 2016-04-29 09:15 UTC
