### ISSUE TITLE
Inserting header doesn't work

### ISSUE THREAD

**Issue by fhoenig** [rubicon-oss/LicenseHeaderManager#5] opened 2015-08-20 17:37 UTC
![2015-08-20 10_36_40-unboundalpha - microsoft visual studio](https://cloud.githubusercontent.com/assets/362728/9390678/651b7e88-4727-11e5-9278-007fc7e103b0.png)

This is VC2013 Community Edition. I get this error on insert.

**Comment by FlorianDecker** [comment] 2015-08-21 12:17
Hi florian,
thanks for the bug report!

We havent tested the License Header Manager with the Community Edition of VS2013.
Before we set up a testing environment, could you clarify under which circumstances this error occurs? 

Does it happen when adding a new File with the option "Insert License Header to new files automatically" enabled?
Or does it happen everytime you try to add a licenseheader to a file within the context menu of the project item/folder/project/solution?

Regards,
FlorianDecker

**Comment by FlorianDecker** [comment] 2015-08-24 07:57
Hi florian, 

i tested it on a VS2013 Community Editions Instance and could not reproduce this error. 

Maybe it occurs only on a specific file extension or project type? 
Please provide me with the needed information so we can tackle down this bug :)

Regards,
FlorianDecker

**Comment by fhoenig** [comment] 2015-08-25 21:13
Hi Florian,

Thanks for getting back. I would like to use this extension eventually.
Check the screenshot attached. That's what I got in terms of extensions.

Best,
Florian

[image: Inline image 1]

**Comment by fhoenig** [comment] 2015-08-25 21:14
Ah also, this is a native Win32 C++ project.

**Comment by FlorianDecker** [comment] 2015-08-27 15:20
Hi,

i could reproduce your issue once randomly. It should be fixed in the current master branch. Because the next official release will take a few weeks, you could try it out by pulling and building the repository. In the bin folder you will find the .vsix file, which applies the Extension to your Visual studio.

You may have to deinstall the LicenseHeaderManager from Visual Studio before installing the new one.

Regards,
Florian

**Comment by fhoenig** [comment] 2015-08-27 15:45
cheers! what was it?

**Comment by FlorianDecker** [comment] 2015-08-28 16:39
Before adding the header, we check the Value of the "IsLink" Property for the Project Item. It seems that it is possible that the project Item does not have this Property and throws an Argument Exception. Sadly i could not figure out which type of Project Item would trigger it, but the Exception gets caught now and everything should be fine.

Please report back if this fixed your Problem so i know for sure :)

**Comment by FlorianDecker** [comment] 2015-09-07 17:21
Fix in 1.6.2

**Closed by FlorianDecker** 2015-09-07 17:21 UTC
