### ISSUE TITLE
Opens a temporary diff file

### ISSUE THREAD

**Issue by avdynut** [rubicon-oss/LicenseHeaderManager#187] opened 2024-12-19 06:39 UTC
When compare files with built-in Visual Studio features, the extension opens a tab with a temporary file, more info here: https://developercommunity.visualstudio.com/t/Comparing-files-shows-a-temporary-file-f/10783182

**Comment by MichaelKetting** [comment] 2024-12-19 07:40
@avdynut this might be a duplicate of #176

**Comment by avdynut** [comment] 2024-12-19 07:42
@MichaelKetting Exactly, thanks

**Comment by MichaelKetting** [comment] 2024-12-19 12:16
I'll close it as a duplicate then.

**Closed as completed by MichaelKetting** 2024-12-19 12:16 UTC
Labels: bug, duplicate
